### PR TITLE
Update items_lang.php

### PR DESCRIPTION
**Pull request by rjobeirne**
This is a trivial change.
It is also necessary to modify the configuration (database) to 
a) change each entry in the list to include a dash e.g. "i7-" to prompt user to include chipset and 
b) change the tile of Custom Field 3 from "CPU Type" to "CPU / Chipset

### CODE REVIEW

**Review by josh-tf — APPROVED** [review]
I can't see the change for the title of the custom field 3, not sure if it was mised in this pull request
Cheers

**Comment by rjobeirne** [comment]
I couldn't see how to make changes to the database recorded it git. Justin didn't know either. I put the note there to remind us to change the configuration locally. Can you explain how we do it in git.

**Review by h00pl4 — APPROVED** [review]

**Comment by h00pl4** [comment]
@josh-tf, do you have any recommendations as to how we apply changes to the database? I suspect that the changes that Richard has made to `deploy/database/cbvpos_import.sql` will only affect the dev environment. Do we have a strategy in place for database migrations on prod?

**Comment by josh-tf** [comment]
> @josh-tf, do you have any recommendations as to how we apply changes to the database? I suspect that the changes that Richard has made to `deploy/database/cbvpos_import.sql` will only affect the dev environment. Do we have a strategy in place for database migrations on prod?

@h00pl4 yeah thats right, any changes to that file will only affect new installations - in the past I've either done the changes manually via cli (on the mariadb container) or via PHPMyadmin
Do we have the details for PMA in Psonos?

**Comment by h00pl4** [comment]
Hey @josh-tf , thanks for the prompt response - apologies for my tardy one. Yes PMA deets are in Psono.

Alright, I'll back up the DB and apply manually this time. Bigger piece to add automated database migration.

**Comment by h00pl4** [comment]
I've updated `app_config.cbvopt_item_cpu` and `app_config.custom3_name` as per PR

**Comment by h00pl4** [comment]
Code change pulled to production 
image

**Pull request merged**
