### PR TITLE
Fix the build process

### PR DESCRIPTION
**Pull request by h00pl4**
* Change npm package "grunt-script-link-tags" to be fetched by https:// rather than git:// which was phased out on GitHub as of 2022-03-15 https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
* Fetch bower package "file-saver.js" from https://github.com/eligrey/FileSaver.js.git as https://github.com/Teleborder/FileSaver.js no longer exists
* Use version 0.5.0-beta4 of bower package "html2canvas" explicitly, as later versions assume a Node environment
* Remove the override for bower package "table-export" as it seems unnecessary
* Add "coffeescript" as a npm package dev dependency, which is reported as a missing dependency in the Grunt logs

Before:
image
image

After:
image
image

### CODE REVIEW

**Comment by rjobeirne** [comment]
That's got it working for me. Just have to remember to clear the browser cache.

**Review by rjobeirne — APPROVED** [review]
That's got it working for me when I remember to clear the browser cache.

**Comment by h00pl4** [comment]
> That's got it working for me when I remember to clear the browser cache.

Hot tip: If you open the Developer Tools panel (`F12` in Chrome) and go to the Network tab, you can check a box to disable the cache which is effective whilst the panel is open
image

**Review by junlinz2 — COMMENTED** [review]
For `app/application/views/partial/header.php`, please keep the line endings consistent, as the added lines in this file are using CRLF (not LF). I would convert these back to LF (for Unix systems).

**Comment by h00pl4** [comment]
Ah, interesting! Thanks for picking that up @junlinz2.  `app/application/views/partial/header.php` is auto-updated by the build process, so I wonder what's happened there? 🤔 As in, why isn't it consistent?

**Comment by junlinz2** [comment]
@h00pl4 did you make these changes on a Windows machine (or have CRLF configured in your editor)? It's possible you opened this file specifically and saved it with CRLF endings. If not, then the only other things I can think of would be something in this build process touches this file (maybe some node.js plugin that for some reason hardcodes its output with CRLF endings). It's hard for me to say what it could be without understanding fully what this build process is and how it's touching this file.

**Comment by h00pl4** [comment]
Hey @junlinz2, I think you're right - I must have saved the file locally, with my editor set to use CRLF, as I realise now that sections of the file that are automatically generated are using LFs, correctly.

**Pull request merged**
