### PR TITLE
Fix the build process _again_

### PR DESCRIPTION
**Pull request by h00pl4**
As of Monday, 24 April 2023 at 11:43:54, Bower renewed their LetsEncrypt SSL certificate. This new certificate uses an intermediate certificate that is unknown to the Docker Image being used to build the CSS and javascript components of OSPOS. As such, Bower (a package manager) was failing to download packages due to an expired SSL certificate. Thankfully, https://stackoverflow.com/a/76102466/43874 provided a workaround.

Before:
image

After:
image
image
image

Also fixed up the inconsistent line endings that @junlinz2 picked up on.

### CODE REVIEW

**Comment by rjobeirne** [comment]
Do I need to test this? If so do I just rebuild my system with the rebuild script with the -f option?

**Comment by h00pl4** [comment]
> Do I need to test this? If so do I just rebuild my system with the rebuild script with the -f option?

Hey @rjobeirne, if you're able to test, that would be great, thank you. Yes, you will need to use the rebuild script with the `-f` option. If you run the rebuild script, whilst on the `master` branch, you should find that the `cbv-dev-pos-build-nodejs` container exits with a non-zero result code (as shown in my screenshot above). If you then checkout this branch (`Build-Fix-2`) and run the rebuild script again, you should find that the `cbv-dev-pos-build-nodejs` now exits with a zero result code.

**Comment by rjobeirne** [comment]
I tried running the rebuild script and could not see much difference. I don't get much detail of what's going on but here is what I got. The first time I ran it with the master branch and the second with Build-Fix-2.
Screenshot from 2023-05-01 14-14-40

**Comment by h00pl4** [comment]
> I tried running the rebuild script and could not see much difference. I don't get much detail of what's going on but here is what I got. The first time I ran it with the master branch and the second with Build-Fix-2. Screenshot from 2023-05-01 14-14-40

Hey @rjobeirne, you should be able to see the same error that I did, by running `docker-compose logs cbv-dev-pos-build-nodejs` after running the rebuild script.

**Review by rjobeirne — APPROVED** [review]
I get the same log messages as you (once I know where look) without the CERT_HAS_EXPIRED message after your mod is included.

**Pull request merged**
