### PR TITLE
Use git to provide the application version

### PR DESCRIPTION
**Pull request by h00pl4**
Use git to provide the version number of OSPOS, based on the output of [`git describe`](https://git-scm.com/docs/git-describe) which will return the name of the tag on the current commit. If the current commit does not have a tag, then it will find the first ancestor with a tag and append to its name the number of commits that have occurred since then, along with the start of the hash of the current commit.

In this way, we can simply tag a commit in the repository with the next version number, and when we deploy that tag, the version number will be reported by OPOS as the application version:

image
Here we can see that I currently have the branch `GetVersionFromGit` checked out, with commit hash `2a1d3e22adde153d8ca5aac04a70615c1a39cce8` and it is two commits ahead of commit hash `00de788e7c3f49321cc398f4787f4e7c883fcf45` which has the tag `v1.2.4`, which is the commit that is currently deployed in production.

image
Now when I run OPSOS, the version is shown as `v1.2.4-2-g2a1d3e22a` because the current commit that I have checked out doesn't have a tag, but 2 commits ago is the tag `v1.2.4` and the start of the current commit's hash is `2a1d3e22a`. (The "g" is a constant prefix for the hash to denote "git"). Granted, including the hash is pretty ugly, but I would only ever expect us to be working on a non-tagged commit when developing locally. We should ever deploy tagged commits to _production_, eg. `v1.2.4`.

Also, the reason for prefixing the version with "v" is so that I can filter out non-version tags that might exist in the repo.

And if you have uncommitted changes in your working directory "-dirty" will be appended to the end of the version.

### CODE REVIEW

**Comment by h00pl4** [comment]
Are you happy with this change @rjobeirne . Any questions?

**Comment by rjobeirne** [comment]
As discussed I'm happy with the intent however it doesn't work on my installation. The version no longer appears on the login screen and is just "source" on subsequent screens.
Screenshot from 2023-06-09 11-07-21
Screenshot from 2023-06-09 11-05-22

**Comment by h00pl4** [comment]
> As discussed I'm happy with the intent however it doesn't work on my installation. The version no longer appears on the login screen and is just "source" on subsequent screens. Screenshot from 2023-06-09 11-07-21 Screenshot from 2023-06-09 11-05-22

Sorry @rjobeirne , missed your reply somehow. Can you please confirm which branch you have checked out and that you refreshed the site after changing to my branch?

**Comment by rjobeirne** [comment]
I tried again with the same result. I confirm I am on the correct branch and the browser was fully refreshed with clear history.
Screenshot from 2023-08-11 10-28-02

**Comment by h00pl4** [comment]
> I tried again with the same result. I confirm I am on the correct branch and the browser was fully refreshed with clear history. Screenshot from 2023-08-11 10-28-02

How curious... Can you please show me the output of the following command on your machine:
```bash
git status
```

**Comment by rjobeirne** [comment]
Here it is.
Screenshot from 2023-08-22 15-43-31

**Comment by h00pl4** [comment]
I'm inclined to merge this, as it's working for me and I see this as a low-risk change.

**Comment by h00pl4** [comment]
I think I know why this isn't working for you @rjobeirne. To run the development environment, Josh instructs you to:

> Copy the `docker-compose` file from inside the cloned directory and create the stack:
> ```sh
> cp ./cbv-pos/deploy/docker/development/docker-compose.yml .
> docker-compose up -d
> ```

But my PR included a change to `./cbv-pos/deploy/docker/development/docker-compose.yml`, so unless you re-copied the file after checking out my branch, you're using an old version of `docker-compose.yml`, which won't have my changes in it.

**Comment by rjobeirne** [comment]
That fixed it. I should have noticed that the .yml file had changed.

**Pull request merged**
