### PR TITLE
Add bank details to invoice

### PR DESCRIPTION
**Pull request by rjobeirne**
Response to Trello item 179. 
Another field added in Office->Config->Invoice for entering the bank details. This will then appear on the invoice. The general message has been modified to include 14 day payment terms.
Formatting could be improved.

### CODE REVIEW

**Comment by h00pl4** [comment]
Hey @rjobeirne, can I please suggest that you include screenshots of your changes, so that I make sure that I'm seeing the same things when I review?

**Comment by h00pl4** [comment]
Ok, I think I understand what we're doing. We're adding additional information to the invoice template to include our bank details. We've achieved this by adding a configurable field to the Invoice template. Given that there is already the "Default Invoice Comments" field, can we not just add the bank details to this existing field instead?

At this stage, I don't see the need for this code change. It would be adding complexity unnecessarily.

**Comment by rjobeirne** [comment]
You are quite right - I don't know what I was thinking. There is however some code change required as per my latest commit to increase the size of the Default Invoice comments box from it's current 3 rows to 9 rows otherwise the message doesn't show completely. The result looks like this on my machine.
Screenshot from 2023-05-01 15-36-54

**Review by h00pl4 — APPROVED** [review]
Ah, I see. Makes sense. Happy with this.

**Pull request merged**
