### PR TITLE
Bank transfer

### PR DESCRIPTION
**Pull request by rjobeirne**
This change is to include Bank Transfer as a method of payment. The reports are also updated to include bank transfers
Trello tquPhsww

### CODE REVIEW

**Review by h00pl4 — APPROVED** [review]
Looks good @rjobeirne! Sorry for taking 14 months to review! 😅

**Comment by h00pl4** [comment]
Don't forget that this is ready to merge @rjobeirne

**Comment by rjobeirne** [comment]
I didn't realise I was responsible to merge my approved PRs. I will do so from now on.

**Comment by h00pl4** [comment]
> I didn't realise I was responsible to merge my approved PRs. I will do so from now on.

Ah, fair enough @rjobeirne. Yes, I'd suggest that it is a good practise for the PR creator to be responsible for merging their PR, as there may be other actions that need to be performed once the PR is merged, that only the creator is aware of. This is most relevant in a development scenario which has Continuous Deployments setup, whereby every commit to the master branch is automatically deployed to an environment. Less of concern for us, as we don't have that setup, but still worth practising I would say.

**Comment by h00pl4** [comment]
I'd also suggest that we delete the source branch once it has been merged, to reduce clutter. Any further changes that are required should be made on a new branch.

**Pull request merged**
